export const APP = "/",
	LOGIN = "/",
	FORGOT_PASSWORD = "/forgot-password",
	PASSWORD_RECOVERY = "/password-recovery",
	EMAIL_VERIFICATION = "/email-verification",
	CHOOSE_TREATMENT = "/choose-treatment",
	CHOOSE_PLAN = "/choose-plan",
	CREATE_PROFILE = "/create-profile",
	DEMOGRAPHICS = "/demographics",
	QUESTIONNAIRE = "/questionnaire",
	BILLING = "/billing",
	CHART = "/chart",
	Home = "/home",
	PATIENT_VIDEOCALLING = "/videoCalling",
	ABOUT_US = "/about-us",
	CONTACT_US = "/contact-us";

export const PASWORD_MATCHER = /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*])(?=.{8,})/;

export const CONSTANTS = {
	PROFILE_SUCCESS_PAYMENT:
		"Your order has been placed, log in to your portal to select an appointment time",
	PROFILE_SUCCESS:
		"Your profile has been created successfully but payment failed.Please try again after login",
	TREATMENT_HEADER: "Back to Home Page",
	TREATMENT_TITLE: "Choose a treatment",
	TREATMENT_SUBTITLE:
		"Choose a treatement that you would like to be treated for you can add or remove treatments later.",
	PLAN_HEADER: "Back to treatments",
	PLAN_TITLE: "Pick the best plan for you",
	PLAN_SUBTITLE:
		"Choose a plan that is right for you, you can always change the later.",
	PROFILE_HEADER: "Back to plans",
	PROFILE_TITLE: "Step 1: Create Profile",
	PROFILE_SUBTITLE: "Create a profile",
	DEMOGRAPHICS_HEADER: "Back to Step 1",
	DEMOGRAPHICS_TITLE: "Step 2: Demographics",
	DEMOGRAPHICS_SUBTITLE: "Fill out demographic information",
	QUESTIONNAIRE_HEADER: "Back to Step 2",
	QUESTIONNAIRE_TITLE: "Step 3: Medical Questionnaire",
	QUESTIONNAIRE_SUBTITLE:
		"Just some medical questions regarding your prescription request",
	BILLING_HEADER: "Back to Step 3",
	BILLING_TITLE: "Step 4: Billing",
	BILLING_SUBTITLE:
		"Don’t worry, we won’t charge you until the prescription has been approved by our medical team and on its way",
	FORGOT_PSWD_TITLE: "Email Sent !",
	FORGOT_PSWD_SUBTITLE:
		"Please check your inbox, we sent the code on your register email.",
	THANK_YOU: "Thank you!",
	CHART_HEADER: "My Chart",
	CURRENT_MED: "Current Medications",
	EDIT_PROFILE: "Edit Profile",
	EDIT_BILLING_HEADER: "Billing",
	EDIT_BILLING: "Edit Billing Infomation",
	ORDER_HEADER: "Orders",
	UPCOMING_ORD: "Upcoming Order",
	ORD_HIST: "Order History",
	MED_INFO_HEADER: "Update Medical Information",
	MED_INFO_TITLE: "Medical Questionnaire",
	REQ_CALL_HEADER: "Request a Call",
	UPLOAD_DOC: "Upload Documents",
	UPLOAD_FILE: "Upload a File",
	ADD_CARD_DETAILS: "Card details",
	MSG_ADD_PAYMENT: "Kindly add the card details",
	ORDER_TABLE_TITLE: "Order History",
	UPLOAD_TABLE_TITLE: "Uploaded Files",
	CHARTS_MODAL_SUBTITLE: "We have saved your information",
	REQ_PAYMENT: "Kindly complete your payment first",
	BILLING_MODAL_SUBTITLE: "We have saved your information",
	Medical_MODAL_SUBTITLE: "We have saved your information",
	FILE_UPLOAD: "Your document has been stored successfully",
	SET_APPOINTMENT: "Your appointment has been made!",
	APPOINTMENT_MSG:
		"we will text and email you to remind you for your appointment",
	REJECT_APPOINTMENT: "Sorry your appointment has not been set",
	SEARCH_PATIENT: "Search Patient",
	EVALUATIONS: "Evaluations",
	NEW_REQUESTS: "New Requests",
	//PATIENT_CHART: "Patient Chart",
	HISTORY: "History",
	ACCEPTED_REQUESTS: "Accepted Requests",
	EVALUATION_TABLEHEADING: "Today's Evaluations",
	SEARCH_TABLE_TITLE: "Results",
	CHART_TABLEHEADING: "Order History",
	PATIENT_REPORTS: "Patient Reports",
	CHART_PAGE_HEADING: "Name(Age)",
	SIGN_CHARTS: "Sign Charts",
	SIGN_CHARTS_TABLE_TITLE: "Charts",
	//RECORDS_TABLEHEADING:"All Reports",
	PATIENT_LIST : "Patient List",
	PHYSICIAN_LIST : "Physician List",
};
